<a href="https://colab.research.google.com/github/LuchithaP/ML/blob/main/TensoeFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow



In [2]:
import numpy

In [3]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [4]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)


Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Create Tensors

In [5]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [6]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [7]:
tf.rank(rank1_tensor)


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [9]:
rank2_tensor.shape

TensorShape([2, 2])

# Change Shape

In [14]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3,-1]) #-1 to calculate the dimension in that place

In [15]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Evaluating Tensors

In [12]:

# Disable eager execution to mimic TensorFlow 1.x behavior
#tf.compat.v1.disable_eager_execution()

# Create a constant tensor
#tenso = tf.constant(10)

# Use tf.compat.v1.Session() to evaluate the tensor
#with tf.compat.v1.Session() as sess:
    #value = tenso.eval()
    #print(value)  # Output: 10


In [ ]:
t = tf.zeros([5,5,5])
print(t)
t = tf.reshape(t, [125])
print(t.numpy())
t= tf.reshape(t, [125,-1])
print(t)


